### ISSUE TITLE
Windows not supported

### ISSUE THREAD

**Issue by Admiral-Enigma** [tursodatabase/libsql-laravel#3]
I can install the package but I get an error message that my OS is not supported. This message is also shown when trying to run migrations.

I'm on Windows 11 64-bit
![image](https://github.com/user-attachments/assets/4e1f8cee-6ec4-4418-ab4b-d6ff8e804a29)

**Comment by x7ryan** [comment]
Can confirm, I got this too.

**Comment by levydsa** [comment]
This will be fixed soon! There is already a solution on the way, expect to be able to run it next patch.

**Comment by levydsa** [comment]
@Admiral-Enigma @x7ryan Can you guys check out the latest version?

**Comment by x7ryan** [comment]
@levydsa 

Just tried, got the following error when trying to generate the autoload file after installing.

```
In functions.php line 23:
                                                                                                                                                              
  [FFI\Exception]                                                                                                                                             
  Failed loading 'C:\Users\Ryan\Herd\ms-portal\vendor\turso\libsql\src/../lib/x86_64-pc-windows-gnu/liblibsql.dll' (The specified module could not be found)  
```

Full output:

```
composer require turso/libsql-laravel
./composer.json has been updated
Running composer update turso/libsql-laravel
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking turso/libsql (v0.2.1)
  - Locking turso/libsql-laravel (v0.1.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading turso/libsql (v0.2.1)
  - Downloading turso/libsql-laravel (v0.1.2)
  - Installing turso/libsql (v0.2.1): Extracting archive
  - Installing turso/libsql-laravel (v0.1.2): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump

In functions.php line 23:
                                                                                                                                                              
  [FFI\Exception]                                                                                                                                             
  Failed loading 'C:\Users\Ryan\Herd\ms-portal\vendor\turso\libsql\src/../lib/x86_64-pc-windows-gnu/liblibsql.dll' (The specified module could not be found)  
                                                                                                                                                              

Exception trace:
  at C:\Users\Ryan\Herd\ms-portal\vendor\turso\libsql\src\functions.php:23
 FFI::cdef() at C:\Users\Ryan\Herd\ms-portal\vendor\turso\libsql\src\functions.php:23
 Libsql\getFFI() at C:\Users\Ryan\Herd\ms-portal\vendor\turso\libsql\src\functions.php:40
 require() at C:\Users\Ryan\Herd\ms-portal\vendor\composer\autoload_real.php:41
 {closure}() at C:\Users\Ryan\Herd\ms-portal\vendor\composer\autoload_real.php:45
 ComposerAutoloaderInitbea448420e8f473fee76aac18fc7d9c9::getLoader() at C:\Users\Ryan\Herd\ms-portal\vendor\autoload.php:25
 require_once() at C:\Users\Ryan\Herd\ms-portal\vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php:43
 Illuminate\Foundation\ComposerScripts::postAutoloadDump() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:491
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:276
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:131
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:473
 Composer\Autoload\AutoloadGenerator->dump() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/Installer.php:362
 Composer\Installer->run() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/Command/RequireCommand.php:498
 Composer\Command\RequireCommand->doUpdate() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/Command/RequireCommand.php:340
 Composer\Command\RequireCommand->execute() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/Console/Application.php:396
 Composer\Console\Application->doRun() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/src/Composer/Console/Application.php:136
 Composer\Console\Application->run() at phar://C:/Users/Ryan/.config/herd/bin/composer.phar/bin/composer:98
 require() at C:\Users\Ryan\.config\herd\bin\composer.phar:29

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDI
T-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-p
latform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

**Comment by levydsa** [comment]
Hey! @x7ryan, dumb mistake in the build file. I was copying `liblibsql.dll` while the name should be `libsql.dll`. I'll push a fix soon.

**Comment by levydsa** [comment]
@x7ryan, should be fixed now. https://github.com/tursodatabase/libsql-php/tree/b334959e7de72f7bfb4a971310290069374a86b5/lib/x86_64-pc-windows-gnu

**Comment by x7ryan** [comment]
@levydsa The file is there now, but I am still getting an error that it cannot be loaded. After looking into it further seems to be a system specific issue. My computer is missing a dependency that libsql.dll requires, specifically, `libgcc_s_seh-1.dll`. 

I can try to find that dll and get it added to my system, but I have a suspicion that this will cause issues for other Windows users, unless it would be possible for you to bundle it in too?

**Comment by levydsa** [comment]
@x7ryan, thanks for the feedback. The library is compiled with MinGW, I'm doing some research on making it work with MSVCRT.

**Comment by darkterminal** [comment]
@levydsa Using Windows 2019 from GitHub runner I think can solved this problem.

**Comment by discoverlance-com** [comment]
I am experiencing a similar issue mentioned by @x7ryan on windows. 

Find full logs below:

```
In functions.php line 25:
                                                                                                                   
  [FFI\Exception]                                                                                                  
  Failed loading 'C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\turso\libsql\src/../lib/x86_64-pc-wind   
  ows-gnu/libsql.dll' (The specified module could not be found)                                                    
                                                                                                                   

Exception trace:
  at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\turso\libsql\src\functions.php:25
 FFI::cdef() at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\turso\libsql\src\functions.php:25
 Libsql\getFFI() at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\turso\libsql\src\functions.php:43
 require() at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\composer\autoload_real.php:41
 {closure}() at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\composer\autoload_real.php:45
 ComposerAutoloaderInit7510620b89818f42516ffa8e94959120::getLoader() at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\autoload.php:25
 require_once() at C:\Users\Lenovo\Herd\laravel-quick-shift-website\vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php:43
 Illuminate\Foundation\ComposerScripts::postAutoloadDump() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:499
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:284
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:139
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php:473
 Composer\Autoload\AutoloadGenerator->dump() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/Installer.php:362
 Composer\Installer->run() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/Command/RequireCommand.php:498
 Composer\Command\RequireCommand->doUpdate() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/Command/RequireCommand.php:340
 Composer\Command\RequireCommand->execute() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/Console/Application.php:397
 Composer\Console\Application->doRun() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/src/Composer/Console/Application.php:137
 Composer\Console\Application->run() at phar://C:/Users/Lenovo/.config/herd/bin/composer.phar/bin/composer:98      
 require() at C:\Users\Lenovo\.config\herd\bin\composer.phar:29

```
